### ISSUE TITLE
Tagging of Markdown text

### ISSUE THREAD

**Issue by matthiasmengel** [matthiasmengel/isimip3a-protocol-mockup#1]
For reduction of the text to the parts relevant to specific text, we need to implement filtering via javascript. 
This would work in plain html, i.e. via http://api.jquery.com/filter/. The main text is however written in markdown, so we would like to set the tags for the filter there. Any idea how this could be implemented?

**Comment by rgieseke** [comment]
Markdown is rendered to HTML and you can usually embed arbitrary HTML (depending on your renderer).

One way could be to add something like

```html
<div class="topic topic-crops">Crops</div>
```

to your document.

The class `topic` could trigger rendering your "Tag" in some way and your JS code would hide or show the sections where this is used. Depends a bit on how you want or need to select the sections though.

**Comment by matthiasmengel** [comment]
Ok, puhh!
Could you/we try that directly on the index.md? So we could show the others. I will create some sections and let you know. These should then disappear if they do not belong to the topic searched for.

**Comment by matthiasmengel** [comment]
@rgieseke I pushed an index md with some html tags. Could you help to filter this with a small filter bar on the topics at the very beginning? This bar and the js would probably go to _layouts/default.html . Do you have an idea for content that should only show if *no* filter is set? So as soon as a selection is done, this text should disappear. 

Maybe an empty

``` html
<div class="topic "></div>
```
is enough. 

Thanks!!!

**Comment by rgieseke** [comment]
It's been a while since i fought with Jekyll but i can give this a look ...

**Comment by matthiasmengel** [comment]
Cool! I think you can even do without fighting the jekyll. Injecting the filtering in `_layouts/default.html` may do the trick.

**Comment by rgieseke** [comment]
I'm still not sure i fully understand the target ...
Currently the protocol is well integrated in the ISIMIP webpage with downloadable PDFs.

Do you want both HTML and PDFs in the end? Should the final version be integrated in a similar manner?

If you just want to write on GitHub you could write the sections in separate Markdown files and combine them in the right order into separate HTML and PDFs with Pandoc.
```
introduction.md
common-input-data.md
agriculture.md
...
```
Using something like here https://stackoverflow.com/questions/4779582/markdown-and-including-multiple-files or pandoc-include

**Comment by matthiasmengel** [comment]
I would treat that as a "web first" project. We can think of PDF later.

The idea that one could either see the full protocol, or filter for specific sectors.
This filter would help modellers that run a sector specific model, as they would see a
shortened version of the manuscript, with only the relevant context for them.

Sure, we will split up chapters into markdown, but beyond that, it would be great
to be able to tag and filter parts of the text, so that sector-specific protocoll versions
are fast to produce.

Have a look at the current isimip2a protocol for example:

https://www.isimip.org/documents/328/ISIMIP2a_protocol_1Mar2018.pdf

Can you quickly grasp the relevant parts for you? No!
The task is to overcome this. Is this clearer?

Thanks again!

**Comment by rgieseke** [comment]
I played a bit with Pandoc and starting from the Manubot template: 

https://rgieseke.github.io/isi-proto/index.html

https://github.com/rgieseke/isi-proto

**Comment by matthiasmengel** [comment]
thanks for this! will discuss with the others.

**Comment by rgieseke** [comment]
Maybe also worth taking a look at https://open.nytimes.com/we-built-a-collaborative-documentation-site-deploy-your-own-with-the-push-of-a-button-134de99c42fc

Uses Google Docs as a backend for a documentation site.

**Comment by rgieseke** [comment]
Now with top navigation and hiding of complete sections (incl. header):

https://rgieseke.github.io/isi-proto/index.html
